name: Build Checks for Pilot

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Bun Runtime
        uses: antongolub/action-setup-bun@v1
      - run: bun i
      - run: bun run build
      - run: du -sh